initial commit

diff --git a/devstack/lib/nfp b/devstack/lib/nfp
--- a/devstack/lib/nfp
+++ b/devstack/lib/nfp
@@ -1,7 +1,6 @@
 #!/bin/bash
 
 NFPSERVICE_DIR=$DEST/gbp
-DISK_IMAGE_DIR=$DEST/gbp/gbpservice/tests/contrib
 TOP_DIR=$PWD
 
 NEUTRON_CONF_DIR=/etc/neutron
@@ -10,10 +9,18 @@ NEUTRON_CONF=$NEUTRON_CONF_DIR/neutron.conf
 NFP_CONF_DIR=/etc/nfp
 echo "TOP-DIR-NFP : $PWD"
 
+function create_nfp_image {
+    TOP_DIR=$TOP_DIR
+    sudo python $DISK_IMAGE_DIR/diskimage-create/disk_image_create.py $DISK_IMAGE_DIR/diskimage-create/conf.json
+    BUILT_IMAGE_PATH=$(cat /tmp/nfp_image_path)
+    upload_image file://$BUILT_IMAGE_PATH
+
+    openstack --os-cloud=devstack-admin flavor create --ram 512 --disk 3 --vcpus 1 m1.nfp-tiny
+}
+
 function prepare_nfp_image_builder {
-    #setup_develop $NFPSERVICE_DIR
-    sudo -H -E pip install -r $DISK_IMAGE_DIR/diskimage-create/requirements.txt
-    sudo apt-get install -y --force-yes qemu-utils
+    setup_develop $NFPSERVICE_DIR
+    sudo -H -E pip install -r $NFPSERVICE_DIR/diskimage-create/requirements.txt
 }
 
 function init_nfpgbpservice {
@@ -31,15 +38,6 @@ function install_nfpgbpservice {
     mv $NFPSERVICE_DIR/_test-requirements.txt $NFPSERVICE_DIR/test-requirements.txt
 }
 
-function create_nfp_image {
-    TOP_DIR=$TOP_DIR
-    sudo python $DISK_IMAGE_DIR/diskimage-create/disk_image_create.py $DISK_IMAGE_DIR/diskimage-create/conf.json
-    BUILT_IMAGE_PATH=$(cat /tmp/nfp_image_path)
-    upload_image file://$BUILT_IMAGE_PATH $TOKEN
-
-    openstack --os-cloud=devstack-admin flavor create --ram 512 --disk 3 --vcpus 1 m1.nfp-tiny
-}
-
 function assign_user_role_credential {
     TOP_DIR=$TOP_DIR
     source $TOP_DIR/openrc admin admin
@@ -52,8 +50,7 @@ function assign_user_role_credential {
 }
 
 function namespace_delete {
-    TOP_DIR=$TOP_DIR
-    source $TOP_DIR/openrc neutron service
+    source $1/openrc neutron service
     #Deletion namespace
     NFP_P=`sudo ip netns | grep "nfp-proxy"`
     if [ ${#NFP_P} -ne 0 ]; then
@@ -79,9 +76,8 @@ function namespace_delete {
 }
 
 function namespace_create {
-    TOP_DIR=$TOP_DIR
-    #doing it in namespace_delete, so no need to do it again
-    #source $1/openrc neutron service
+
+    source $1/openrc neutron service
     SERVICE_MGMT_NET="l2p_svc_management_ptg"
     cidr="/24"
     echo "Creating new namespace nfp-proxy...."
@@ -115,7 +111,7 @@ function namespace_create {
         echo "Neutron port creation failed (check source) "
         exit 0
     else
-        echo "New Neutron Port Created on Service management network with ip =$new_ip"
+        echo "New Neuteon Port Created on Service management network with ip =$new_ip"
     fi
     new_ip_cidr+="$new_ip/24"
     sleep 2
@@ -138,9 +134,9 @@ function namespace_create {
     #get tag_id  form port in ovs-bridge
     tag_id=`sudo ovs-vsctl list port $port | grep "tag" | tail -n 1 | awk '{print $3}'`
 
-    sudo ovs-vsctl set port pt1 tag=$tag_id
+    sudo ovs-vsctl set port pt1 tag=$tag_id     
 
-    #up the both ports
+    #up the both ports 
     sudo ip netns exec nfp-proxy ip link set pt0 up
     sudo ip netns exec nfp-proxy ip link set lo up
     sudo ip link set pt1 up
@@ -150,44 +146,28 @@ function namespace_create {
     then
         echo "nfp-proxy namespcace creation success and reaching to $2"
     else
-        echo "Fails reaching to $2"
+        echo "Fails reaching to $2" 
     fi
 
     sudo ip netns exec nfp-proxy /usr/bin/nfp_proxy --config-file=/etc/nfp_proxy.ini
 }
 
 function create_nfp_gbp_resources {
+   
    TOP_DIR=$TOP_DIR
    source $TOP_DIR/openrc neutron service
-
-   if [[ $DISABLE_BUILD_IMAGE = False ]]; then
-       IMAGE_PATH=$(cat /tmp/nfp_image_path)
-       IMAGE_NAME=`basename "$IMAGE_PATH"`
-       IMAGE_NAME_FLAT="${IMAGE_NAME%.*}"
-       FLAVOR=m1.nfp-tiny
-   else
-       IMAGE_NAME_FLAT="reference_configurator_image"
-       FLAVOR=m1.small
-   fi
    gbp network-service-policy-create --network-service-params type=ip_pool,name=vip_ip,value=nat_pool svc_mgmt_fip_policy
-   gbp service-profile-create --servicetype LOADBALANCER --insertion-mode l3 --shared True --service-flavor service_vendor=haproxy,device_type=None --vendor NFP base_mode_lb
-   gbp service-profile-create --servicetype FIREWALL --insertion-mode l3 --shared True --service-flavor service_vendor=nfp,device_type=nova,image_name=$IMAGE_NAME_FLAT,flavor=$FLAVOR --vendor NFP base_mode_fw_vm
+
+   gbp service-profile-create --servicetype LOADBALANCER --insertion-mode l3 --shared True --service-flavor service_vendor=haproxy,device_type=nova --vendor NFP lb_profile
+   gbp service-profile-create --servicetype FIREWALL --insertion-mode l3 --shared True --service-flavor service_vendor=vyos,device_type=nova --vendor NFP fw_profile
+
    gbp group-create svc_management_ptg --service_management True
+
 }
 
-function get_router_namespace {
-    TOP_DIR=$TOP_DIR
-    source $TOP_DIR/openrc neutron service
-
-    GROUP="svc_management_ptg"
-    echo "GroupName: $GROUP"
-
-    l2p_id=`gbp ptg-show svc_management_ptg | grep l2_policy_id | awk '{print $4}'`
-    l3p_id=`gbp l2p-show $l2p_id | grep l3_policy_id | awk '{print $4}'`
-    RouterId=`gbp l3p-show $l3p_id | grep routers | awk '{print $4}'`
-}
 
 function copy_nfp_files_and_start_process {
+
     TOP_DIR=$TOP_DIR
     cd /opt/stack/gbp/gbpservice/nfp
     sudo cp -r  bin/nfp /usr/bin/
@@ -199,13 +179,12 @@ function copy_nfp_files_and_start_process {
     sudo cp -r  bin/proxy.ini /etc/nfp_proxy.ini
     sudo cp -r  bin/nfp_proxy /usr/bin/
 
-    IpAddr=127.0.0.1
+
     echo "Configuring proxy.ini .... with rest_server_address as $IpAddr"
     sudo sed -i "s/rest_server_address=*.*/rest_server_address=$IpAddr/g" /etc/nfp_proxy.ini
-    sudo sed -i "s/rest_server_port= *.*/rest_server_port=8080/g" /etc/nfp_proxy.ini
+    sudo sed -i "s/rest_server_port= *.*/rest_server_port=8070/g" /etc/nfp_proxy.ini
     ipnetns_router=`sudo ip netns |grep $RouterId`
 
-    sed -i 's#source.*#source '$TOP_DIR'/openrc demo demo#g' /opt/stack/gbp/devstack/exercises/nfp_service/*.sh
     source $TOP_DIR/functions-common
 
     echo "Starting orchestrator  >>>> under screen named : orchestrator"
@@ -217,13 +196,11 @@ function copy_nfp_files_and_start_process {
     sleep 1
 
     echo "Starting proxy server under Namespace : nfp-proxy namespace >>>> under screen named : proxy"
-    run_process proxy "source /opt/stack/gbp/devstack/lib/nfp;namespace_delete $TOP_DIR;namespace_create $TOP_DIR $IpAddr"
+    run_process proxy "source $TOP_DIR/lib/nfp;namespace_delete $TOP_DIR;namespace_create $TOP_DIR $IpAddr"
     sleep 10
 
-    cd base_configurator/api
-    sudo python setup.py develop
-    echo "Starting base_configurator  >>>> under screen named : base_configurator"
-    run_process base_configurator "cd /opt/stack/gbp/gbpservice/nfp/base_configurator/api;sudo ip netns exec nfp-proxy pecan serve config.py"
+    echo "Starting config_orch  >>>> under screen named : config_orch"
+    run_process config_orch "sudo /usr/bin/nfp  --config-file /etc/nfp_config_orch.ini --config-file /etc/neutron/neutron.conf --log-file /opt/stack/logs/nfp_config_orch.log"
     sleep 1
 
     echo "Running gbp-db-manage"
@@ -233,4 +210,104 @@ function copy_nfp_files_and_start_process {
     gbp-db-manage --config-file /etc/neutron/neutron.conf upgrade head
     sleep 2
     echo "Configuration success ... "
+
+}
+
+function create_ext_net {
+    TOP_DIR=$TOP_DIR
+    source $TOP_DIR/stackrc
+    EXT_NET_NAME=$EXT_NET_NAME
+    EXT_NET_SUBNET_NAME=$EXT_NET_SUBNET_NAME
+    EXT_NET_GATEWAY=$EXT_NET_GATEWAY
+    EXT_NET_ALLOCATION_POOL_START=$EXT_NET_ALLOCATION_POOL_START
+    EXT_NET_ALLOCATION_POOL_END=$EXT_NET_ALLOCATION_POOL_END
+    EXT_NET_CIDR=$EXT_NET_CIDR
+    EXT_NET_MASK=$EXT_NET_MASK
+    
+    source $TOP_DIR/openrc neutron service
+    neutron net-create --router:external=true --shared $EXT_NET_NAME
+    neutron subnet-create --ip_version 4 --gateway $EXT_NET_GATEWAY --name $EXT_NET_SUBNET_NAME --allocation-pool start=$EXT_NET_ALLOCATION_POOL_START,end=$EXT_NET_ALLOCATION_POOL_END $EXT_NET_NAME $EXT_NET_CIDR/$EXT_NET_MASK
+    subnet_id=`neutron net-list | grep "$EXT_NET_NAME" | awk '{print $6}'`
+
+}
+
+function upload_images_and_launch_configuratorVM {
+
+    TOP_DIR=$TOP_DIR
+    source $TOP_DIR/openrc neutron service
+    ConfiguratorQcow2ImageName=$ConfiguratorQcow2Image
+    VyosQcow2Image=$VyosQcow2Image
+    HaproxyQcow2Image=$HaproxyQcow2Image
+    ConfiguratorImageName=configurator
+    VyosImageName=vyos
+    HaproxyImageName=haproxy
+    if [ ! -z "$TOP_DIR" -a "$TOP_DIR" != " " ]; then
+        echo "Uploading Image : $ConfiguratorImageName"
+        glance image-create --name $ConfiguratorImageName --disk-format qcow2  --container-format bare  --visibility public --file $ConfiguratorQcow2ImageName
+        echo "Uploading Image : $VyosImageName"
+        glance image-create --name $VyosImageName --disk-format qcow2  --container-format bare  --visibility public --file $VyosQcow2Image
+        echo "Uploading Image : $HaproxyImageName"
+        glance image-create --name $HaproxyImageName --disk-format qcow2  --container-format bare  --visibility public --file $HaproxyQcow2Image
+    else
+        echo "ImageName not provided ..."
+        exit
+    fi
+
+    InstanceName="configuratorVM_instance"
+
+    GROUP="svc_management_ptg"
+    echo "GroupName: $GROUP"
+    PortId=$(gbp policy-target-create --policy-target-group $GROUP $InstanceName | grep port_id  | awk '{print $4}')
+
+    echo "Collecting ImageId : for $ConfiguratorImageName"
+    ImageId=`glance image-list|grep $ConfiguratorImageName |awk '{print $2}'`
+    if [ ! -z "$ImageId" -a "$ImageId" != " " ]; then
+        echo $ImageId
+    else
+        echo "No image found with name $ConfiguratorImageName ..."
+        exit
+    fi
+
+    nova boot --flavor m1.medium --image $ImageId --nic port-id=$PortId $InstanceName
+    sleep 10
+
+    l2p_id=`gbp ptg-show svc_management_ptg | grep l2_policy_id | awk '{print $4}'`
+    l3p_id=`gbp l2p-show $l2p_id | grep l3_policy_id | awk '{print $4}'`
+    RouterId=`gbp l3p-show $l3p_id | grep routers | awk '{print $4}'`
+
+    echo "Collecting RouterId : for $RouterName"
+    if [ ! -z "$RouterId" -a "$RouterId" != " " ]; then
+        echo $RouterId
+    else
+        echo "Router creation failed with $RouterName ..."
+        exit
+    fi
+
+    echo "Get IpAddr with port: $PortId"
+    IpAddr_extractor=`neutron port-list|grep $PortId|awk '{print $11}'`
+    IpAddr_purge_last=${IpAddr_extractor::-1}
+    IpAddr=${IpAddr_purge_last//\"/}
+    echo "Collecting IpAddr : for $PortId"
+    echo $IpAddr
+
+}
+
+function nfp_logs_forword {
+    VISIBILITY_CONF="/etc/rsyslog.d/visibility.conf"
+    SYSLOG_CONFIG="/etc/rsyslog.conf"
+    log_facility=local1
+
+    sudo sed -i '/#$ModLoad imudp/ s/^#//' $SYSLOG_CONFIG
+    sudo sed -i '/#$UDPServerRun 514/ s/^#//' $SYSLOG_CONFIG
+    echo "Successfully enabled UDP in syslog"
+
+    visibility_vm_ip_address=$IpAddr
+    echo "$log_facility.*                @$visibility_vm_ip_address:514" | sudo tee -a $VISIBILITY_CONF
+    echo "Created $VISIBILITY_CONF file" 
+
+    sudo service rsyslog restart
+    if [ $? -ne 0 ]; then
+        echo "ERROR: Failed to restart rsyslog"
+    fi 
+
 }
